---
title: "p8105_hw5_cev2129"
output: html_document
date: "2024-11-14"
---

```{r}
library(tidyverse)
library(rvest)
set.seed(1)
``` 

##Problem 2

```{r}
q2_t_test = function(mu, iterations = 5000) { 
  replicate(iterations, {
    data <- rnorm(n = 30, mean = mu, sd = 5)
    t_test <- t.test(data, mu = 0) 
    broom::tidy(t_test)  
  }, simplify = FALSE) |>
    bind_rows() |>
    mutate(mu = mu)
}

values = c(0, 1, 2, 3, 4, 5, 6) 

q2_results = map_dfr(values, q2_t_test) 

q2_power = q2_results |>
  group_by(mu) |>
  summarize(
    mean_estimate = mean(estimate),
    power = mean(p.value < 0.05)
  )

q2_power
```

```{r}
library(ggplot2)
ggplot(q2_power, aes(x = mu, y = power)) + 
  geom_point()
```

```{r}
null_rejected = q2_results |>
  group_by(mu) |>
  summarize(
    mean_rejected = mean(estimate[p.value < 0.05], na.rm = TRUE)  
  )

q2 = q2_power |>
  left_join(null_rejected, by = "mu")

q2
```

```{r}
plot1 = ggplot(q2, aes(x = mu)) +
  geom_line(aes(y = mean_estimate), color = "red",linetype = "solid") +
  geom_point(aes(y = mean_estimate), color = "red")
plot1

plot2 = plot1 + geom_line(aes(y = mean_rejected), color = "yellow", linetype = "dashed") +
  geom_point(aes(y = mean_rejected), size = 3, color = "yellow") 

plot2
```
##Problem 3
```{r}
library(dplyr)
library(readr)

homicide_data = read_csv("https://raw.githubusercontent.com/washingtonpost/data-homicides/refs/heads/master/homicide-data.csv")

homicide_data = homicide_data |>
  mutate(city_state = paste(city, state, sep = ", "))

summary = homicide_data |>
  group_by(city_state) |>
  summarize(
    total = n(),  
    unsolved = sum(disposition %in% c("Closed without arrest", "Open/No arrest"))  
  )
summary
``` 
```{r}
baltimore = homicide_data |>
  filter(city_state == "Baltimore, MD")

prop_test <- prop.test(
  x = sum(baltimore[["disposition"]] %in% c("Closed without arrest", "Open/No arrest")), 
  n = nrow(baltimore)) |>
  broom::tidy()
```
